site_name: Gluster Docs V2
site_url: https://docsv2.gluster.org/
site_description: Project documentation for Gluster

repo_url: https://github.com/poornimag/glusterdocs-V2/
docs_dir: docs

nav:
- Home: index.md
theme:
  name: 'Bootswatch '
extra_javascript:
- js/fix-docs.js
