site_name: Gluster Docs V2
site_url: https://docsv2.gluster.org/
site_description: Project documentation for Gluster

repo_url: https://github.com/poornimag/glusterdocs-V2/
docs_dir: docs

nav:
- Home: about-gluster.md
- Quick Start Guide:
    - GlusterFS: Quick Start Guide/glusterfs.md
    - Gluster Block: Quick Start Guide/gluster-block.md
    - Gluster Object: Quick Start Guide/gluster-object.md
    - Gluster Container Storage: Quick Start Guide/gluster-container-storage.md
    - Gluster For Hyperconverged Infrastructure: Quick Start Guide/gluster-ovirt.md
- Install Guide:
    - Prerequisites: Install Guide/prerequisites.md
    - Install GlusterFS: Install Guide/install-glusterfs.md
- Administration Guideinistration Guide:
    - Prerequisites:
       - Add Firewall Rules: Administration Guide/firewall-rules.md
       - Create Storage Pool: Administration Guide/create-storage-pool.md
       - Create Bricks: Administration Guide/create-bricks.md
    - Volume Create:
       - Dsitribute: Administration Guide/distribute.md
       - Replicate: Administration Guide/replicate.md
       - Distribute-Replicate: Administration Guide/distribute-replicate.md
       - Disperse: Administration Guide/disperse.md
       - Distribute-Disperse: Administration Guide/distribute-disperse.md
       - Sharded Volume: Administration Guide/shard.md
    - Volume Management:
       - Volume lifecycle: Administration Guide/volume-lifecycle.md
       - Volume Configurations: Administration Guide/volume-configurations.md
       - Expanding Volume: Administration Guide/expanding_volume.md
       - Shrinking Volume: Administration Guide/shrinking_volume.md
       - Rebalance: Administration Guide/rebalance.md
       - Replacing bricks: Administration Guide/replace_bricks.md
       - Scale Up Disperse By One: Administration Guide/scale-up-desperse-by-one.md
       - Scale Up Storage: Administration Guide/scale-up-storage.md
       - Scale Down Storage: Administration Guide/scale-down-storage.md
       - Self Heal Volume Data: Administration Guide/self-heal.md
    - Access Mechanisms:
       - File Access:
          - FUSE: Administration Guide/fuse.md
          - SMB: Administration Guide/smb.md
          - NFS: Administration Guide/NFS_Ganesha.md
          - API: Amd/gfapi.md
       - Block Access: Administration Guide/block-access.md
       - Object Access: Administration Guide/object.md
    - Performance Tunables:
       - Kernel Performance Tunables: Administration Guide/kernel-perfoamance-tunables.md
       - Workload specific Tunables:
          - Small Files: Administration Guide/small-files.md
          - Large Files: Administration Guide/large-files.md
          - Hyperconverged Setup: Administration Guide/hyperconverged-setup.md
    - Key Data Services:
       - Geo Replication: Administration Guide/geo-replication.md
       - Snapshot: Administration Guide/snapshot.md
       - Bitrot Detection: Administration Guide/bitrot-detection.md
       - Shard For Large Files: Administration Guide/shard-for-large-files.md
       - Cloud-Sync: Administration Guide/cloud-sync.md
       - SSL: Administration Guide/ssl.md
       - WORM: Administration Guide/worm.md
       - Compression: Administration Guide/compression.md
       - GfProxy: Administration Guide/gfproxy.md
    - Monitoring Tools:
       - Grafana: Administration Guide/grafana.md
       - Eventing: Administration Guide/eventing.md
       - Gstatus: Administration Guide/gstatus.md
    - Troubleshooting:
       - Performance Issues: Administration Guide/performance.md
       - Replace Brick: Administration Guide/replace-brick.md
       - Heal/Split Brain Issues: Administration Guide/heal-issues.md
       - High Memory Consumption: Administration Guide/high-memory-consumption.md
       - Data Collection for Reporting: Administration Guide/data-collection-for-Reporting.md
       - Logs: Administration Guide/logs.md
       - Gluster Internal Store: Administration Guide/gluster-internal-store.md
       - Gluster Processes: Administration Guide/gluster-processes.md
       - GFID To Path: Administration Guide/gfid-to-path.md
       - FAQs: Administration Guide/FAQs.md
    - Integration With Other Ecosystem:
       - Hadoop: Administration Guide/hadoop.md
       - Bareos: Administration Guide/bareos.md
       - ZFS: Administration Guide/zfs.md
    - Glossory: Administration Guide/glossory.md

theme:
  name: 'material'
extra_javascript:
- js/fix-docs.js
